/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

/**
 *
 * @author iGimenezSan
 */
public class ConexionBBDD extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConexionBBDD
     */
    public ConexionBBDD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_seccion1 = new javax.swing.JLabel();
        fieldname_dbName1 = new javax.swing.JLabel();
        textfield_dbName1 = new javax.swing.JTextField();
        fieldname_url1 = new javax.swing.JLabel();
        textfield_url1 = new javax.swing.JTextField();
        fieldname_username1 = new javax.swing.JLabel();
        textfield_username1 = new javax.swing.JTextField();
        fieldname_password1 = new javax.swing.JLabel();
        textfield_password1 = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        title_seccion2 = new javax.swing.JLabel();
        fieldname_dbName2 = new javax.swing.JLabel();
        textfield_dbName2 = new javax.swing.JTextField();
        fieldname_url2 = new javax.swing.JLabel();
        textfield_url2 = new javax.swing.JTextField();
        fieldname_port2 = new javax.swing.JLabel();
        textfield_port2 = new javax.swing.JTextField();
        fieldname_username2 = new javax.swing.JLabel();
        textfield_username2 = new javax.swing.JTextField();
        fieldname_password2 = new javax.swing.JLabel();
        textfield_password2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Conexion a Base de Datos");

        title_seccion1.setText("Acceso a Base de Datos Local");

        fieldname_dbName1.setText("Nombre BD");

        textfield_dbName1.setText("catalogws");

        fieldname_url1.setText("URL");

        textfield_url1.setText("jdbc:mysql://localhost:3306/");

        fieldname_username1.setText("Usuario");

        textfield_username1.setText("root");

        fieldname_password1.setText("Password");

        textfield_password1.setText("root");

        title_seccion2.setText("Acceso a Base de Datos Real");

        fieldname_dbName2.setText("Nombre BD");

        textfield_dbName2.setText("catalogws");

        fieldname_url2.setText("URL");

        textfield_url2.setText("mysql.loading.es");

        fieldname_port2.setText("Puerto");

        textfield_port2.setText("3360");

        fieldname_username2.setText("Usuario");

        textfield_username2.setText("mckyavelik");

        fieldname_password2.setText("Password");

        textfield_password2.setText("unk yet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldname_dbName1)
                                            .addComponent(fieldname_username1))
                                        .addGap(97, 97, 97)
                                        .addComponent(fieldname_url1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textfield_dbName1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(title_seccion1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(textfield_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldname_password1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfield_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield_url1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldname_username2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fieldname_dbName2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textfield_dbName2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldname_url2))
                                    .addComponent(title_seccion2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(textfield_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldname_password2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textfield_password2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(textfield_url2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldname_port2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfield_port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(separador1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_seccion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_dbName1)
                    .addComponent(textfield_dbName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_url1)
                    .addComponent(textfield_url1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_username1)
                    .addComponent(textfield_username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_password1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_seccion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_dbName2)
                    .addComponent(textfield_dbName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_url2)
                    .addComponent(textfield_url2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_port2)
                    .addComponent(textfield_port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_username2)
                    .addComponent(textfield_username2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_password2))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fieldname_dbName1;
    private javax.swing.JLabel fieldname_dbName2;
    private javax.swing.JLabel fieldname_password1;
    private javax.swing.JLabel fieldname_password2;
    private javax.swing.JLabel fieldname_port2;
    private javax.swing.JLabel fieldname_url1;
    private javax.swing.JLabel fieldname_url2;
    private javax.swing.JLabel fieldname_username1;
    private javax.swing.JLabel fieldname_username2;
    private javax.swing.JSeparator separador1;
    private javax.swing.JTextField textfield_dbName1;
    private javax.swing.JTextField textfield_dbName2;
    private javax.swing.JTextField textfield_password1;
    private javax.swing.JTextField textfield_password2;
    private javax.swing.JTextField textfield_port2;
    private javax.swing.JTextField textfield_url1;
    private javax.swing.JTextField textfield_url2;
    private javax.swing.JTextField textfield_username1;
    private javax.swing.JTextField textfield_username2;
    private javax.swing.JLabel title_seccion1;
    private javax.swing.JLabel title_seccion2;
    // End of variables declaration//GEN-END:variables
}
