package interfazGrafica;

import javax.swing.JOptionPane;
import toolbox.ConectoresBDD;
import toolbox.Descargadores;
import toolbox.Utilidades;

/**
 *
 * @author iGimenezSan
 */
public class Parametros extends javax.swing.JInternalFrame {
    
    private static final Descargadores DOWN = new Descargadores();
    private static final ConectoresBDD BBDD = new ConectoresBDD();
    private static final Utilidades UTIL = new Utilidades();
    
    /**
     * Creates new form Parametros
     */
    public Parametros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panel_info_General = new javax.swing.JPanel();
        title_seccion2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfield_driverName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panel_info_Local = new javax.swing.JPanel();
        title_seccion1 = new javax.swing.JLabel();
        fieldname_url1 = new javax.swing.JLabel();
        textfield_urlBaseDatosLocal = new javax.swing.JTextField();
        fieldname_dbName1 = new javax.swing.JLabel();
        textfield_NombreBaseDatosLocal = new javax.swing.JTextField();
        fieldname_username1 = new javax.swing.JLabel();
        textfield_NombreUsuarioLocal = new javax.swing.JTextField();
        fieldname_password1 = new javax.swing.JLabel();
        textfield_PasswordUsuarioLocal = new javax.swing.JTextField();
        panel_info_website = new javax.swing.JPanel();
        title_seccion3 = new javax.swing.JLabel();
        fieldname_dbName2 = new javax.swing.JLabel();
        fieldname_url2 = new javax.swing.JLabel();
        textfield_url2 = new javax.swing.JTextField();
        textfield_dbName2 = new javax.swing.JTextField();
        fieldname_port2 = new javax.swing.JLabel();
        textfield_port2 = new javax.swing.JTextField();
        fieldname_username2 = new javax.swing.JLabel();
        textfield_username2 = new javax.swing.JTextField();
        fieldname_password2 = new javax.swing.JLabel();
        textfield_password2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        Panel2ProdGlobal2 = new javax.swing.JPanel();
        fieldname_Global2 = new javax.swing.JLabel();
        fieldname_DestinoGlobal2 = new javax.swing.JLabel();
        fieldname_EstructuraCampos2 = new javax.swing.JLabel();
        fieldname_DestinoEstructuraCampos2 = new javax.swing.JLabel();
        textfield_Global_URL = new javax.swing.JTextField();
        textfield_Global_Destino = new javax.swing.JTextField();
        textfield_CamposGlobal_URL = new javax.swing.JTextField();
        textfield_CamposGlobal_Destino = new javax.swing.JTextField();
        button_Descargar_Global = new javax.swing.JToggleButton();
        button_Descargar_Campos_Global = new javax.swing.JToggleButton();
        button_Guardar_Global = new javax.swing.JButton();
        button_Mostrar_Global = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        textfield_destinoStock = new javax.swing.JTextField();
        textfield_destinoExpired = new javax.swing.JTextField();
        fieldname_destinoStock = new javax.swing.JLabel();
        textfield_latest = new javax.swing.JTextField();
        textfield_stock = new javax.swing.JTextField();
        fieldname_stock = new javax.swing.JLabel();
        fieldname_latest = new javax.swing.JLabel();
        fieldname_destinoLatest = new javax.swing.JLabel();
        fieldname_noStock = new javax.swing.JLabel();
        textfield_destinoLatest = new javax.swing.JTextField();
        textfield_noStock = new javax.swing.JTextField();
        fieldname_destinoNoStock = new javax.swing.JLabel();
        textfield_destinoNoStock = new javax.swing.JTextField();
        fieldname_destinoOffers = new javax.swing.JLabel();
        fieldname_expired = new javax.swing.JLabel();
        textfield_destinoOffers = new javax.swing.JTextField();
        textfield_expired = new javax.swing.JTextField();
        fieldname_offers = new javax.swing.JLabel();
        fieldname_destinoExpired = new javax.swing.JLabel();
        textfield_offers = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Parametros");

        title_seccion2.setText("Informacion General");

        jLabel1.setText("Drivername");

        textfield_driverName.setText("com.mysql.jdbc.Driver");

        javax.swing.GroupLayout panel_info_GeneralLayout = new javax.swing.GroupLayout(panel_info_General);
        panel_info_General.setLayout(panel_info_GeneralLayout);
        panel_info_GeneralLayout.setHorizontalGroup(
            panel_info_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_GeneralLayout.createSequentialGroup()
                .addComponent(title_seccion2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_info_GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_driverName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_info_GeneralLayout.setVerticalGroup(
            panel_info_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_GeneralLayout.createSequentialGroup()
                .addComponent(title_seccion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_info_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfield_driverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        title_seccion1.setText("Acceso a Base de Datos Local");

        fieldname_url1.setText("URL Local");

        textfield_urlBaseDatosLocal.setText("jdbc:mysql://localhost:3306/");

        fieldname_dbName1.setText("Nombre BD");

        textfield_NombreBaseDatosLocal.setText("catalogws");

        fieldname_username1.setText("Usuario");

        textfield_NombreUsuarioLocal.setText("root");

        fieldname_password1.setText("Password");

        textfield_PasswordUsuarioLocal.setText("root");

        javax.swing.GroupLayout panel_info_LocalLayout = new javax.swing.GroupLayout(panel_info_Local);
        panel_info_Local.setLayout(panel_info_LocalLayout);
        panel_info_LocalLayout.setHorizontalGroup(
            panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_LocalLayout.createSequentialGroup()
                .addComponent(title_seccion1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_info_LocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_info_LocalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fieldname_url1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldname_dbName1)
                    .addGroup(panel_info_LocalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(fieldname_username1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_info_LocalLayout.createSequentialGroup()
                        .addComponent(textfield_NombreUsuarioLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldname_password1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_PasswordUsuarioLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textfield_NombreBaseDatosLocal)
                    .addComponent(textfield_urlBaseDatosLocal))
                .addContainerGap())
        );
        panel_info_LocalLayout.setVerticalGroup(
            panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_LocalLayout.createSequentialGroup()
                .addComponent(title_seccion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_url1)
                    .addComponent(textfield_urlBaseDatosLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_dbName1)
                    .addComponent(textfield_NombreBaseDatosLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_PasswordUsuarioLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_password1))
                    .addGroup(panel_info_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_username1)
                        .addComponent(textfield_NombreUsuarioLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        title_seccion3.setText("Acceso a Base de Datos Real");

        fieldname_dbName2.setText("Nombre BD");

        fieldname_url2.setText("URL Local");

        textfield_url2.setText("mysql.loading.es");
        textfield_url2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_url2ActionPerformed(evt);
            }
        });

        textfield_dbName2.setText("catalogws");

        fieldname_port2.setText("Puerto");

        textfield_port2.setText("3360");

        fieldname_username2.setText("Usuario");

        textfield_username2.setText("mckyavelik");

        fieldname_password2.setText("Password");

        textfield_password2.setText("unk yet");

        javax.swing.GroupLayout panel_info_websiteLayout = new javax.swing.GroupLayout(panel_info_website);
        panel_info_website.setLayout(panel_info_websiteLayout);
        panel_info_websiteLayout.setHorizontalGroup(
            panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_websiteLayout.createSequentialGroup()
                .addComponent(title_seccion3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_info_websiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldname_url2)
                    .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_dbName2)
                        .addComponent(fieldname_username2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_info_websiteLayout.createSequentialGroup()
                        .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_dbName2)
                            .addComponent(textfield_url2))
                        .addGap(18, 18, 18)
                        .addComponent(fieldname_port2))
                    .addGroup(panel_info_websiteLayout.createSequentialGroup()
                        .addComponent(textfield_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldname_password2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_port2)
                .addContainerGap())
        );
        panel_info_websiteLayout.setVerticalGroup(
            panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_websiteLayout.createSequentialGroup()
                .addComponent(title_seccion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_url2)
                    .addComponent(textfield_url2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_port2)
                    .addComponent(textfield_port2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldname_dbName2)
                    .addComponent(textfield_dbName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panel_info_websiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_username2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_username2)
                    .addComponent(textfield_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldname_password2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Recalcular Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Grabar en BDD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_info_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panel_info_Local, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_info_website, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 370, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_info_General, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_info_Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_info_website, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Conexion a BBDD", jPanel2);

        jTabbedPane3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane3FocusGained(evt);
            }
        });

        fieldname_Global2.setText("Global");

        fieldname_DestinoGlobal2.setText("Destino Local");

        fieldname_EstructuraCampos2.setText("Estructura Campos");

        fieldname_DestinoEstructuraCampos2.setText("Destino Local");

        textfield_Global_URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_Global_URLActionPerformed(evt);
            }
        });

        textfield_Global_Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_Global_DestinoActionPerformed(evt);
            }
        });

        textfield_CamposGlobal_Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_CamposGlobal_DestinoActionPerformed(evt);
            }
        });

        button_Descargar_Global.setIcon(new javax.swing.ImageIcon("D:\\WS_Updater\\src\\imgs\\down.gif")); // NOI18N
        button_Descargar_Global.setText("Descargar");
        button_Descargar_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Descargar_GlobalActionPerformed(evt);
            }
        });

        button_Descargar_Campos_Global.setIcon(new javax.swing.ImageIcon("D:\\WS_Updater\\src\\imgs\\down.gif")); // NOI18N
        button_Descargar_Campos_Global.setText("Descargar");
        button_Descargar_Campos_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Descargar_Campos_GlobalActionPerformed(evt);
            }
        });

        button_Guardar_Global.setText("Guardar");
        button_Guardar_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Guardar_GlobalActionPerformed(evt);
            }
        });

        button_Mostrar_Global.setText("Mostrar");
        button_Mostrar_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Mostrar_GlobalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2ProdGlobal2Layout = new javax.swing.GroupLayout(Panel2ProdGlobal2);
        Panel2ProdGlobal2.setLayout(Panel2ProdGlobal2Layout);
        Panel2ProdGlobal2Layout.setHorizontalGroup(
            Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2ProdGlobal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldname_DestinoEstructuraCampos2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldname_EstructuraCampos2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldname_DestinoGlobal2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldname_Global2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Panel2ProdGlobal2Layout.createSequentialGroup()
                        .addComponent(button_Mostrar_Global, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Guardar_Global, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfield_CamposGlobal_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfield_CamposGlobal_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfield_Global_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfield_Global_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_Descargar_Campos_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Descargar_Global, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        Panel2ProdGlobal2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textfield_CamposGlobal_Destino, textfield_CamposGlobal_URL, textfield_Global_Destino, textfield_Global_URL});

        Panel2ProdGlobal2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_Guardar_Global, button_Mostrar_Global});

        Panel2ProdGlobal2Layout.setVerticalGroup(
            Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2ProdGlobal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2ProdGlobal2Layout.createSequentialGroup()
                        .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfield_Global_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldname_Global2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfield_Global_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldname_DestinoGlobal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfield_CamposGlobal_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldname_EstructuraCampos2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldname_DestinoEstructuraCampos2)
                            .addComponent(textfield_CamposGlobal_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2ProdGlobal2Layout.createSequentialGroup()
                        .addComponent(button_Descargar_Global, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Descargar_Campos_Global, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Panel2ProdGlobal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_Guardar_Global, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(button_Mostrar_Global, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Panel2ProdGlobal2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textfield_CamposGlobal_Destino, textfield_CamposGlobal_URL, textfield_Global_Destino, textfield_Global_URL});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2ProdGlobal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2ProdGlobal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Fichero Global", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rutas a Ficheros", jPanel1);

        textfield_destinoStock.setText("c:\\FicherosGrutinet\\Stock.csv");
        textfield_destinoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_destinoStockActionPerformed(evt);
            }
        });

        textfield_destinoExpired.setText("c:\\FicherosGrutinet\\SinStock.csv");
        textfield_destinoExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_destinoExpiredActionPerformed(evt);
            }
        });

        fieldname_destinoStock.setText("Ruta Local Destino");

        textfield_latest.setText("http://media.grutinet.com/ficheros/productos_csv_novedades.csv");
        textfield_latest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_latestActionPerformed(evt);
            }
        });

        textfield_stock.setText("http://media.grutinet.com/ficheros/productos_stock.csv");

        fieldname_stock.setText("Stock Actual de Productos");

        fieldname_latest.setText("Lista de Novedades");

        fieldname_destinoLatest.setText("Ruta Local Destino");

        fieldname_noStock.setText("Productos sin Stock");

        textfield_destinoLatest.setText("c:\\FicherosGrutinet\\Novedades.csv");
        textfield_destinoLatest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_destinoLatestActionPerformed(evt);
            }
        });

        textfield_noStock.setText("http://media.grutinet.com/ficheros/productos_csv_sin_stock.csv");

        fieldname_destinoNoStock.setText("Ruta Local Destino");

        textfield_destinoNoStock.setText("c:\\FicherosGrutinet\\SinStock.csv");
        textfield_destinoNoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_destinoNoStockActionPerformed(evt);
            }
        });

        fieldname_destinoOffers.setText("Ruta Local Destino");

        fieldname_expired.setText("Productos Descatalogados");

        textfield_destinoOffers.setText("c:\\FicherosGrutinet\\Ofertas.csv");
        textfield_destinoOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_destinoOffersActionPerformed(evt);
            }
        });

        textfield_expired.setText("http://media.grutinet.com/ficheros/productos_csv_descatalogados.csv");
        textfield_expired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_expiredActionPerformed(evt);
            }
        });

        fieldname_offers.setText("Lista de Ofertas");

        fieldname_destinoExpired.setText("Ruta Local Destino");

        textfield_offers.setText("http://media.grutinet.com/ficheros/productos_csv_ofertas.csv");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldname_destinoLatest, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_destinoOffers, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_destinoStock, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_destinoNoStock, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_destinoExpired, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_expired, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_noStock, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_stock, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_offers, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldname_latest, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textfield_noStock, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfield_stock, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfield_offers, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfield_expired, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(textfield_latest, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfield_destinoLatest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(textfield_destinoOffers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(textfield_destinoStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(textfield_destinoNoStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addComponent(textfield_destinoExpired, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_latest)
                        .addComponent(textfield_latest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_destinoLatest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_destinoLatest))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_offers)
                        .addComponent(textfield_offers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_destinoOffers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_destinoOffers))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_stock)
                        .addComponent(textfield_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_destinoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_destinoStock))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_noStock)
                        .addComponent(textfield_noStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_destinoNoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_destinoNoStock))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldname_expired)
                        .addComponent(textfield_expired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_destinoExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldname_destinoExpired))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textfield_destinoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_destinoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_destinoStockActionPerformed

    private void textfield_destinoExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_destinoExpiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_destinoExpiredActionPerformed

    private void textfield_latestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_latestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_latestActionPerformed

    private void textfield_destinoLatestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_destinoLatestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_destinoLatestActionPerformed

    private void textfield_destinoNoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_destinoNoStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_destinoNoStockActionPerformed

    private void textfield_destinoOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_destinoOffersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_destinoOffersActionPerformed

    private void textfield_expiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_expiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_expiredActionPerformed

    private void textfield_url2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_url2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_url2ActionPerformed

    private void button_Guardar_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Guardar_GlobalActionPerformed
        BBDD.actualizarDatosGlobalEnBaseDatos(recogerDatos());
    }//GEN-LAST:event_button_Guardar_GlobalActionPerformed

    private void button_Descargar_Campos_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Descargar_Campos_GlobalActionPerformed
        DOWN.descargaCamposGlobal();
    }//GEN-LAST:event_button_Descargar_Campos_GlobalActionPerformed

    private void button_Descargar_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Descargar_GlobalActionPerformed
        DOWN.descargaGlobal();
    }//GEN-LAST:event_button_Descargar_GlobalActionPerformed

    private void textfield_CamposGlobal_DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_CamposGlobal_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_CamposGlobal_DestinoActionPerformed

    private void textfield_Global_DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_Global_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_Global_DestinoActionPerformed

    private void textfield_Global_URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_Global_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_Global_URLActionPerformed

    private void button_Mostrar_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Mostrar_GlobalActionPerformed
        mostrarDatosGlobal(BBDD.cargarDatosGlobalDesdeBaseDatos());
    }//GEN-LAST:event_button_Mostrar_GlobalActionPerformed

    private void jTabbedPane3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3FocusGained
    
    public String getURLGlobal() {
        String rutaGlobal = textfield_Global_URL.getText();
        return rutaGlobal;
    }
    
    public String getURLCamposGlobal() {
        String rutaCamposGlobal = textfield_CamposGlobal_URL.getText();
        return rutaCamposGlobal;
    }
    
    public String getDestinoLocalGlobal() {
        String destinoLocalGlobal = textfield_Global_Destino.getText();
        return destinoLocalGlobal;
    }
    
    public String getDestinoLocalCamposGlobal() {
        String destinoLocalCamposGlobal = textfield_CamposGlobal_Destino.getText();
        return destinoLocalCamposGlobal;
    }
    
    public String getDriverName() {
        String driverName = textfield_driverName.getText();
        return driverName;
    }
    
    public String getURLBaseDatosLocal() {
        String urlBaseDatosLocal = textfield_urlBaseDatosLocal.getText();
        return urlBaseDatosLocal;
    }
    
    public String getNombreBaseDatosLocal() {
        String NombreBaseDatosLocal = textfield_NombreBaseDatosLocal.getText();
        return NombreBaseDatosLocal;
    }
    
    public String getNombreUsuarioLocal() {
        String NombreUsuarioLocal = textfield_NombreUsuarioLocal.getText();
        return NombreUsuarioLocal;
    }
    
    public String getPasswordUsuarioLocal() {
        String PasswordUsuarioLocal = textfield_PasswordUsuarioLocal.getText();
        return PasswordUsuarioLocal;
    }
    
    public void setRutaGlobal(String valorRutaGlobal) {
        textfield_Global_URL.setText(valorRutaGlobal);
    }
    
    public void setDestinoGlobal (String valorDestinoGlobal) {
        textfield_Global_Destino.setText(valorDestinoGlobal);
    }
    
    public void setRutaCampos (String valorRutaCampos) {
        textfield_CamposGlobal_URL.setText(valorRutaCampos);
    }
    
    public void setDestinoCampos (String valorDestinoCampos) {
        textfield_CamposGlobal_Destino.setText(valorDestinoCampos);
    }
    
    public final void mostrarDatosGlobal(String[] valores) {
        setRutaGlobal(valores[0]);
        setDestinoGlobal(valores[1]);
        setRutaCampos(valores[2]);
        setDestinoCampos(valores[3]);
    }
    
    private String[] recogerDatos() {
        String[] valores = new String[4];
        
        valores [0] = getURLGlobal();
        valores [1] = getDestinoLocalGlobal();
        valores [2] = getURLCamposGlobal();
        valores [3] = getDestinoLocalCamposGlobal();
        
        return valores;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2ProdGlobal2;
    private javax.swing.JToggleButton button_Descargar_Campos_Global;
    private javax.swing.JToggleButton button_Descargar_Global;
    private javax.swing.JButton button_Guardar_Global;
    private javax.swing.JButton button_Mostrar_Global;
    private javax.swing.JLabel fieldname_DestinoEstructuraCampos2;
    private javax.swing.JLabel fieldname_DestinoGlobal2;
    private javax.swing.JLabel fieldname_EstructuraCampos2;
    private javax.swing.JLabel fieldname_Global2;
    private javax.swing.JLabel fieldname_dbName1;
    private javax.swing.JLabel fieldname_dbName2;
    private javax.swing.JLabel fieldname_destinoExpired;
    private javax.swing.JLabel fieldname_destinoLatest;
    private javax.swing.JLabel fieldname_destinoNoStock;
    private javax.swing.JLabel fieldname_destinoOffers;
    private javax.swing.JLabel fieldname_destinoStock;
    private javax.swing.JLabel fieldname_expired;
    private javax.swing.JLabel fieldname_latest;
    private javax.swing.JLabel fieldname_noStock;
    private javax.swing.JLabel fieldname_offers;
    private javax.swing.JLabel fieldname_password1;
    private javax.swing.JLabel fieldname_password2;
    private javax.swing.JLabel fieldname_port2;
    private javax.swing.JLabel fieldname_stock;
    private javax.swing.JLabel fieldname_url1;
    private javax.swing.JLabel fieldname_url2;
    private javax.swing.JLabel fieldname_username1;
    private javax.swing.JLabel fieldname_username2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPanel panel_info_General;
    private javax.swing.JPanel panel_info_Local;
    private javax.swing.JPanel panel_info_website;
    private javax.swing.JTextField textfield_CamposGlobal_Destino;
    private javax.swing.JTextField textfield_CamposGlobal_URL;
    private javax.swing.JTextField textfield_Global_Destino;
    private javax.swing.JTextField textfield_Global_URL;
    private javax.swing.JTextField textfield_NombreBaseDatosLocal;
    private javax.swing.JTextField textfield_NombreUsuarioLocal;
    private javax.swing.JTextField textfield_PasswordUsuarioLocal;
    private javax.swing.JTextField textfield_dbName2;
    private javax.swing.JTextField textfield_destinoExpired;
    private javax.swing.JTextField textfield_destinoLatest;
    private javax.swing.JTextField textfield_destinoNoStock;
    private javax.swing.JTextField textfield_destinoOffers;
    private javax.swing.JTextField textfield_destinoStock;
    private javax.swing.JTextField textfield_driverName;
    private javax.swing.JTextField textfield_expired;
    private javax.swing.JTextField textfield_latest;
    private javax.swing.JTextField textfield_noStock;
    private javax.swing.JTextField textfield_offers;
    private javax.swing.JTextField textfield_password2;
    private javax.swing.JTextField textfield_port2;
    private javax.swing.JTextField textfield_stock;
    private javax.swing.JTextField textfield_url2;
    private javax.swing.JTextField textfield_urlBaseDatosLocal;
    private javax.swing.JTextField textfield_username2;
    private javax.swing.JLabel title_seccion1;
    private javax.swing.JLabel title_seccion2;
    private javax.swing.JLabel title_seccion3;
    // End of variables declaration//GEN-END:variables



}
