/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

/**
 *
 * @author iGimenezSan
 */


public class VentanaPrincipal extends javax.swing.JFrame {

//    public DescargaFicheros TOOL_DOWNLOAD = new DescargaFicheros();
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
//        inicioSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemProductos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemParametros = new javax.swing.JMenuItem();
        menuItemRutas = new javax.swing.JMenuItem();
        menuItemBaseDatos = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WS Updater Control Panel");

        jMenu4.setText("Carga de Datos");

        jMenuItem3.setText("Cargar Productos");
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        menuItemProductos.setText("Actualizar");
        menuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Descargar Ficheros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuItemProductos.add(jMenuItem1);

        jMenuBar1.add(menuItemProductos);

        jMenu1.setText("Configuracion");

        menuItemParametros.setText("Parametros");
        menuItemParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemParametrosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemParametros);

        menuItemRutas.setText("Rutas a Ficheros");
        menuItemRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRutasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRutas);

        menuItemBaseDatos.setText("Conexion a Base de Datos");
        menuItemBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBaseDatosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemBaseDatos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void inicioSesion() {                                                   
        InicioSesion objInicio = new InicioSesion();
        Escritorio.add(objInicio);
        objInicio.show();
    }

    private void menuItemParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemParametrosActionPerformed
        Parametros vent_Parametros = new Parametros();
        Escritorio.add(vent_Parametros);
        vent_Parametros.show();
    }//GEN-LAST:event_menuItemParametrosActionPerformed

    private void menuItemRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRutasActionPerformed
        RutasFicheros vent_Rutas = new RutasFicheros();
        Escritorio.add(vent_Rutas);
        vent_Rutas.show();
    }//GEN-LAST:event_menuItemRutasActionPerformed

    private void menuItemBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBaseDatosActionPerformed
        ConexionBBDD vent_BaseDatos = new ConexionBBDD();
        Escritorio.add(vent_BaseDatos);
        vent_BaseDatos.show();
    }//GEN-LAST:event_menuItemBaseDatosActionPerformed

    private void menuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemProductosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VentanaInternaDescargas vent_Descargadores = new VentanaInternaDescargas();
        Escritorio.add(vent_Descargadores);
        vent_Descargadores.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuItemBaseDatos;
    private javax.swing.JMenuItem menuItemParametros;
    private javax.swing.JMenu menuItemProductos;
    private javax.swing.JMenuItem menuItemRutas;
    // End of variables declaration//GEN-END:variables
}
